//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupermarketFIX
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductInfo_Tab
    {
        public int ProductID { get; set; }
        public string itemName { get; set; }
        public string Categories { get; set; }
        public Nullable<System.DateTime> insertDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
    }
}
